"""second migration

Revision ID: 03b6e3d87ee9
Revises: 
Create Date: 2020-04-27 21:21:57.576697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '03b6e3d87ee9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('covscan19_patients', 'height',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('covscan19_patients', 'hometown',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('covscan19_patients', 'hometown',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('covscan19_patients', 'height',
               existing_type=mysql.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###
