"""Initial migration

Revision ID: 5e9d4b3211d2
Revises: 
Create Date: 2020-04-23 06:16:20.047019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9d4b3211d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('covscan19-users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covscan19-users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('email', sa.VARCHAR(length=80), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=False),
    sa.Column('bio', sa.TEXT(), nullable=True),
    sa.Column('admin', sa.BOOLEAN(), nullable=False),
    sa.CheckConstraint('admin IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
