"""third migration

Revision ID: 6911e90b0799
Revises: 03b6e3d87ee9
Create Date: 2020-04-28 03:29:43.369081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6911e90b0799'
down_revision = '03b6e3d87ee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('date', sa.String(length=25), nullable=False))
    op.drop_column('history', 'record_mode')
    op.drop_column('history', 'timestamp')
    op.add_column('vital_statistics', sa.Column('record_mode', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vital_statistics', 'record_mode')
    op.add_column('history', sa.Column('timestamp', mysql.DATETIME(), nullable=False))
    op.add_column('history', sa.Column('record_mode', mysql.VARCHAR(length=25), nullable=True))
    op.drop_column('history', 'date')
    # ### end Alembic commands ###
