"""fourth migration

Revision ID: 72e59a08bc07
Revises: 6911e90b0799
Create Date: 2020-04-30 09:45:45.533932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '72e59a08bc07'
down_revision = '6911e90b0799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('covscan19_admins', sa.Column('password', sa.String(length=80), nullable=True))
    op.drop_column('covscan19_admins', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('covscan19_admins', sa.Column('admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('covscan19_admins', 'password')
    # ### end Alembic commands ###
