"""updated fifth migration

Revision ID: b189e7d50d33
Revises: a13fa75c1928
Create Date: 2020-05-01 17:26:48.636956

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b189e7d50d33'
down_revision = 'a13fa75c1928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_statistics', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('vital_statistics', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vital_statistics', sa.Column('time', mysql.VARCHAR(length=10), nullable=True))
    op.drop_column('vital_statistics', 'timestamp')
    # ### end Alembic commands ###
